[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' https://apis.google.com https://www.gstatic.com https://cdn.tailwindcss.com 'sha256-Qfss6uYzLa/8emN0ZlP1HBDzIpEYWj4rJg6mITmJT7U=';"